/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RadiologistListView.java
 *
 * Created on 2010.10.04., 12:21:15
 */

package radiologistmodule.view;

import org.jdesktop.swingx.decorator.HighlighterFactory;
import radiologistmodule.iview.IRadiologistListView;
import radiologistmodule.viewmodel.RadiologistListViewModel;

/**
 *
 * @author vincze.attila
 */
public class RadiologistListView extends javax.swing.JInternalFrame implements IRadiologistListView {

    private RadiologistListViewModel viewModel;
    /** Creates new form RadiologistListView */
    public RadiologistListView() {
        viewModel = new RadiologistListViewModel(this);
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
        if (viewModel.getEntityList().size() > 0) {
            setTableSelectionIndex(0);
        }
        tblEntities.addHighlighter(HighlighterFactory.createSimpleStriping());
    }

    public RadiologistListViewModel getViewModel() {
        return viewModel;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnlAction = new javax.swing.JPanel();
        btnNew = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        pnlSearch = new org.jdesktop.swingx.JXTaskPane();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        pnlList = new org.jdesktop.swingx.JXTitledPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEntities = new org.jdesktop.swingx.JXTable();

        setBackground(new java.awt.Color(227, 239, 251));
        setBorder(null);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("radiologistmodule/bundle/RadiologistListBundle"); // NOI18N
        pnlAction.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("RadiologistListView.pnlAction.border.title"))); // NOI18N
        pnlAction.setOpaque(false);
        pnlAction.setLayout(new java.awt.GridBagLayout());

        btnNew.setAction(viewModel.getNewAction());
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radiologistmodule/image/new.png"))); // NOI18N
        btnNew.setText(bundle.getString("RadiologistListView.btnNew.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        pnlAction.add(btnNew, gridBagConstraints);

        btnDelete.setAction(viewModel.getDeleteAction());
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radiologistmodule/image/delete.png"))); // NOI18N
        btnDelete.setText(bundle.getString("RadiologistListView.btnDelete.text")); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.listModeHandler.deleteButtonEnabled}"), btnDelete, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        pnlAction.add(btnDelete, gridBagConstraints);

        btnSelect.setAction(viewModel.getSelectAction());
        btnSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radiologistmodule/image/select.png"))); // NOI18N
        btnSelect.setText(bundle.getString("RadiologistListView.btnSelect.text")); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.listModeHandler.selectButtonEnabled}"), btnSelect, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        pnlAction.add(btnSelect, gridBagConstraints);

        getContentPane().add(pnlAction, java.awt.BorderLayout.PAGE_END);

        jXTaskPaneContainer1.setBorder(null);
        jXTaskPaneContainer1.setLayout(new java.awt.BorderLayout());

        pnlSearch.setTitle(bundle.getString("RadiologistListView.pnlSearch.title")); // NOI18N
        pnlSearch.getContentPane().setLayout(new java.awt.GridBagLayout());

        txtName.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.searchName}"), txtName, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlSearch.getContentPane().add(txtName, gridBagConstraints);

        lblName.setText(bundle.getString("RadiologistListView.lblName.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlSearch.getContentPane().add(lblName, gridBagConstraints);

        btnSearch.setAction(viewModel.getFindAction());
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radiologistmodule/image/search.png"))); // NOI18N
        btnSearch.setText(bundle.getString("RadiologistListView.btnSearch.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        pnlSearch.getContentPane().add(btnSearch, gridBagConstraints);

        jXTaskPaneContainer1.add(pnlSearch, java.awt.BorderLayout.CENTER);

        getContentPane().add(jXTaskPaneContainer1, java.awt.BorderLayout.NORTH);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.message}"), pnlList, org.jdesktop.beansbinding.BeanProperty.create("title"));
        bindingGroup.addBinding(binding);

        pnlList.getContentContainer().setLayout(new java.awt.BorderLayout());

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.entityList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tblEntities);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userInfo.name}"));
        columnBinding.setColumnName("User Info.name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userInfo.loginName}"));
        columnBinding.setColumnName("User Info.login Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${canReport}"));
        columnBinding.setColumnName("Can Report");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${englishAllowed}"));
        columnBinding.setColumnName("English Allowed");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.selectedEntity}"), tblEntities, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tblEntities.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEntitiesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEntities);
        tblEntities.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("RadiologistListView.tblEntities.columnModel.title0")); // NOI18N
        tblEntities.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("RadiologistListView.tblEntities.columnModel.title1")); // NOI18N
        tblEntities.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("RadiologistListView.tblEntities.columnModel.title2")); // NOI18N
        tblEntities.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("RadiologistListView.tblEntities.columnModel.title3")); // NOI18N

        pnlList.getContentContainer().add(jScrollPane2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(pnlList, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblEntitiesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEntitiesMouseClicked
        if (evt.getClickCount() == 2) {
            viewModel.getSelectAction().actionPerformed(null);
        }
    }//GEN-LAST:event_tblEntitiesMouseClicked

    public final void setTableSelectionIndex(int index) {
        tblEntities.getSelectionModel().setSelectionInterval(0, index);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSelect;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlAction;
    private org.jdesktop.swingx.JXTitledPanel pnlList;
    private org.jdesktop.swingx.JXTaskPane pnlSearch;
    private org.jdesktop.swingx.JXTable tblEntities;
    private javax.swing.JTextField txtName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
