/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TroubleshootViewer.java
 *
 * Created on 2010.12.08., 11:31:43
 */
package view;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;
import viewmodel.TroubleshootViewModel;
import converter.ScenarioDeactivateTableCellEditor;
import converter.ScenarioDeactivateTableCellRenderer;
import converter.ScenarioStartTableCellEditor;
import converter.ScenarioStartTableCellRenderer;
import iview.ITroubleshootView;
import javax.swing.UIManager;

/**
 *
 * @author vincze.attila
 */
public class TroubleshootViewOld extends javax.swing.JDialog implements ITroubleshootView {

    private TroubleshootViewModel viewModel;

    /** Creates new form TroubleshootViewer */
    public TroubleshootViewOld(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        viewModel = new TroubleshootViewModel(this);
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TroubleshootViewOld.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(TroubleshootViewOld.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(TroubleshootViewOld.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TroubleshootViewOld.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setSize(1100, 400);
        setAlwaysOnTop(true);
        setLocationRelativeTo(parent);
        addWindowListener(new java.awt.event.WindowAdapter()  {

            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                //System.exit(0);
            }
        });
        setVisible(true);
    }

    public TroubleshootViewModel getViewModel() {
        return viewModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnlScenario = new org.jdesktop.swingx.JXTitledPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblScenario = new org.jdesktop.swingx.JXTable();
        pnlScenarioInstance = new org.jdesktop.swingx.JXTitledPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblScenarioInstance = new org.jdesktop.swingx.JXTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Scenariók");
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pnlScenario.setTitle("Lehetséges scenariók");
        pnlScenario.getContentContainer().setLayout(new java.awt.BorderLayout());

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.scenarioList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tblScenario);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${englishName}"));
        columnBinding.setColumnName("English name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idBehaviourStarted}"));
        columnBinding.setColumnName("");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idBehaviourStarted}"));
        columnBinding.setColumnName("");
        columnBinding.setColumnClass(String.class);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane3.setViewportView(tblScenario);
        tblScenario.getColumnModel().getColumn(1).setCellEditor(new ScenarioStartTableCellEditor("Start"));
        tblScenario.getColumnModel().getColumn(1).setCellRenderer(new ScenarioStartTableCellRenderer());
        tblScenario.getColumnModel().getColumn(2).setCellEditor(new ScenarioDeactivateTableCellEditor("Deactivate"));
        tblScenario.getColumnModel().getColumn(2).setCellRenderer(new ScenarioDeactivateTableCellRenderer());

        pnlScenario.getContentContainer().add(jScrollPane3, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlScenario);

        pnlScenarioInstance.setTitle("Esethez rendelt scenariók");
        pnlScenarioInstance.getContentContainer().setLayout(new java.awt.BorderLayout());

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.scenarioInstanceList}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tblScenarioInstance);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${scenario.englishName}"));
        columnBinding.setColumnName("Scenario");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${added}"));
        columnBinding.setColumnName("Added");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${deactivated}"));
        columnBinding.setColumnName("Deactivated");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${note}"));
        columnBinding.setColumnName("Note");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane4.setViewportView(tblScenarioInstance);

        pnlScenarioInstance.getContentContainer().add(jScrollPane4, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlScenarioInstance);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable()  {

            public void run() {
                TroubleshootViewOld dialog = new TroubleshootViewOld(new javax.swing.JFrame(), true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private org.jdesktop.swingx.JXTitledPanel pnlScenario;
    private org.jdesktop.swingx.JXTitledPanel pnlScenarioInstance;
    private org.jdesktop.swingx.JXTable tblScenario;
    private org.jdesktop.swingx.JXTable tblScenarioInstance;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
