/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TroubleshootView.java
 *
 * Created on 2011.03.31., 17:37:45
 */
package view;

import commonmodule.view.ITSLookAndFeel;
import converter.ScenarioDeactivateTableCellEditor;
import converter.ScenarioDeactivateTableCellRenderer;
import converter.ScenarioStartTableCellEditor;
import converter.ScenarioStartTableCellRenderer;
import iview.ITroubleshootView;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import viewmodel.TroubleshootViewModel;

/**
 *
 * @author vincze.attila
 */
public class TroubleshootView extends javax.swing.JDialog implements ITroubleshootView {

    private TroubleshootViewModel viewModel;

    /** Creates new form TroubleshootView */
    public TroubleshootView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            UIManager.setLookAndFeel(new ITSLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(TroubleshootView.class.getName()).log(Level.SEVERE, null, ex);
        }
        viewModel = new TroubleshootViewModel(this);
        initComponents();
        setSize(1180, 600);
        setAlwaysOnTop(true);
        setLocationRelativeTo(parent);
        addWindowListener(new java.awt.event.WindowAdapter() {

            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
            }
        });
        setVisible(true);
    }

    public TroubleshootViewModel getViewModel() {
        return viewModel;
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblScenario = new org.jdesktop.swingx.JXTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblScenarioInstance = new commonmodule.view.ITSTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(238, 243, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 25, 22, 35, new java.awt.Color(238, 243, 250)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 20, new java.awt.Color(238, 243, 250)));
        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 476));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Scenario types");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 10, 0, new java.awt.Color(238, 243, 250)));
        jPanel3.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblScenario.setBackground(new java.awt.Color(238, 243, 250));
        tblScenario.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblScenario.setColumnMargin(10);
        tblScenario.setGridColor(new java.awt.Color(238, 243, 250));
        tblScenario.setRowHeight(28);
        tblScenario.setRowMargin(10);
        tblScenario.setRowSelectionAllowed(false);
        tblScenario.setShowHorizontalLines(false);
        tblScenario.setShowVerticalLines(false);
        tblScenario.setTableHeader(null);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.scenarioList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tblScenario);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${englishName}"));
        columnBinding.setColumnName("");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idBehaviourStarted}"));
        columnBinding.setColumnName("");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idBehaviourStarted}"));
        columnBinding.setColumnName("");
        columnBinding.setColumnClass(String.class);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblScenario);
        tblScenario.getColumnModel().getColumn(0).setResizable(false);
        tblScenario.getColumnModel().getColumn(0).setPreferredWidth(335);
        tblScenario.getColumnModel().getColumn(1).setResizable(false);
        tblScenario.getColumnModel().getColumn(1).setPreferredWidth(80);
        tblScenario.getColumnModel().getColumn(1).setCellEditor(new ScenarioStartTableCellEditor("Start"));
        tblScenario.getColumnModel().getColumn(1).setCellRenderer(new ScenarioStartTableCellRenderer());
        tblScenario.getColumnModel().getColumn(2).setResizable(false);
        tblScenario.getColumnModel().getColumn(2).setPreferredWidth(105);
        tblScenario.getColumnModel().getColumn(2).setCellEditor(new ScenarioDeactivateTableCellEditor("Deactivate"));
        tblScenario.getColumnModel().getColumn(2).setCellRenderer(new ScenarioDeactivateTableCellRenderer());

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_START);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 20, 0, 0, new java.awt.Color(238, 243, 250)));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Scenarios assigned to this case");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 10, 0, new java.awt.Color(238, 243, 250)));
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.scenarioInstanceList}");
        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tblScenarioInstance);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${scenario.englishName}"));
        columnBinding.setColumnName("Scenario");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${added}"));
        columnBinding.setColumnName("Added");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${deactivated}"));
        columnBinding.setColumnName("Deactivated");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${note}"));
        columnBinding.setColumnName("Note");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane2.setViewportView(tblScenarioInstance);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TroubleshootView dialog = new TroubleshootView(new javax.swing.JFrame(), true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable tblScenario;
    private commonmodule.view.ITSTable tblScenarioInstance;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
