/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CaseEditView.java
 *
 * Created on 2010.11.23., 12:11:52
 */
package casemodule.view;

import casemodule.iview.ICaseEditView;
import casemodule.viewmodel.CaseEditViewModel;
import converter.DateTimeConverter;

/**
 *
 * @author vincze.attila
 */
public class CaseEditView extends javax.swing.JInternalFrame implements ICaseEditView {

    private CaseEditViewModel viewModel;

    /** Creates new form CaseEditView */
    public CaseEditView() {
        viewModel = new CaseEditViewModel(this);
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
    }

    /**
     *
     * @return
     */
    public CaseEditViewModel getViewModel() {
        return viewModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        tbpCase = new javax.swing.JTabbedPane();
        pnlDicomPatientData = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtMothersBirthName = new javax.swing.JTextField();
        txtComments = new javax.swing.JTextField();
        txtOtherPatientNames = new javax.swing.JTextField();
        txtOtherPatientId = new javax.swing.JTextField();
        txtSex = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtTypeOfPatientId = new javax.swing.JTextField();
        txtIssuerOfPatientId = new javax.swing.JTextField();
        txtPatientId = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        patientName = new javax.swing.JLabel();
        patientId = new javax.swing.JLabel();
        issuerOfPatientId = new javax.swing.JLabel();
        typeOfPatientId = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        sex = new javax.swing.JLabel();
        otherPatientId = new javax.swing.JLabel();
        otherPatientNames = new javax.swing.JLabel();
        comments = new javax.swing.JLabel();
        mothersBirthName = new javax.swing.JLabel();
        report = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReport = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(227, 239, 251));
        setBorder(null);
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/casemodule/image/case16.png"))); // NOI18N

        tbpCase.setBackground(new java.awt.Color(227, 239, 251));

        pnlDicomPatientData.setBackground(new java.awt.Color(227, 239, 251));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        txtMothersBirthName.setEditable(false);
        txtMothersBirthName.setPreferredSize(new java.awt.Dimension(200, 20));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.mothersBirthName}"), txtMothersBirthName, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtMothersBirthName, gridBagConstraints);

        txtComments.setEditable(false);
        txtComments.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.comments}"), txtComments, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtComments, gridBagConstraints);

        txtOtherPatientNames.setEditable(false);
        txtOtherPatientNames.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.otherPatientNames}"), txtOtherPatientNames, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtOtherPatientNames, gridBagConstraints);

        txtOtherPatientId.setEditable(false);
        txtOtherPatientId.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.otherPatientId}"), txtOtherPatientId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtOtherPatientId, gridBagConstraints);

        txtSex.setEditable(false);
        txtSex.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.sex}"), txtSex, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtSex, gridBagConstraints);

        txtDob.setEditable(false);
        txtDob.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.dob}"), txtDob, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(new DateTimeConverter());
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtDob, gridBagConstraints);

        txtTypeOfPatientId.setEditable(false);
        txtTypeOfPatientId.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.typeOfPatientId}"), txtTypeOfPatientId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtTypeOfPatientId, gridBagConstraints);

        txtIssuerOfPatientId.setEditable(false);
        txtIssuerOfPatientId.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.issuerOfPatientId}"), txtIssuerOfPatientId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtIssuerOfPatientId, gridBagConstraints);

        txtPatientId.setEditable(false);
        txtPatientId.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.patientId}"), txtPatientId, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtPatientId, gridBagConstraints);

        txtPatientName.setEditable(false);
        txtPatientName.setPreferredSize(new java.awt.Dimension(200, 20));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.patientAndReferralInfo.dicomPatientData.patientName}"), txtPatientName, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 210;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(txtPatientName, gridBagConstraints);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("casemodule/bundle/CaseModuleBundle"); // NOI18N
        patientName.setText(bundle.getString("CaseDetailView.patientName.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(patientName, gridBagConstraints);

        patientId.setText(bundle.getString("CaseDetailView.patientId.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(patientId, gridBagConstraints);

        issuerOfPatientId.setText(bundle.getString("CaseDetailView.issuerOfPatientId.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(issuerOfPatientId, gridBagConstraints);

        typeOfPatientId.setText(bundle.getString("CaseDetailView.typeOfPatientId.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(typeOfPatientId, gridBagConstraints);

        dob.setText(bundle.getString("CaseDetailView.dob.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(dob, gridBagConstraints);

        sex.setText(bundle.getString("CaseDetailView.sex.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(sex, gridBagConstraints);

        otherPatientId.setText(bundle.getString("CaseDetailView.otherPatientId.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(otherPatientId, gridBagConstraints);

        otherPatientNames.setText(bundle.getString("CaseDetailView.otherPatientNames.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(otherPatientNames, gridBagConstraints);

        comments.setText(bundle.getString("CaseDetailView.comments.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(comments, gridBagConstraints);

        mothersBirthName.setText(bundle.getString("CaseDetailView.mothersBirthName.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(mothersBirthName, gridBagConstraints);

        report.setText("report");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(report, gridBagConstraints);

        txtReport.setBackground(new java.awt.Color(240, 240, 240));
        txtReport.setColumns(20);
        txtReport.setEditable(false);
        txtReport.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.tdsCase.finalizedReport}"), txtReport, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(txtReport);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        javax.swing.GroupLayout pnlDicomPatientDataLayout = new javax.swing.GroupLayout(pnlDicomPatientData);
        pnlDicomPatientData.setLayout(pnlDicomPatientDataLayout);
        pnlDicomPatientDataLayout.setHorizontalGroup(
            pnlDicomPatientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDicomPatientDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        pnlDicomPatientDataLayout.setVerticalGroup(
            pnlDicomPatientDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDicomPatientDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        tbpCase.addTab("Dicom Patient Data", pnlDicomPatientData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpCase, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpCase, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comments;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel issuerOfPatientId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mothersBirthName;
    private javax.swing.JLabel otherPatientId;
    private javax.swing.JLabel otherPatientNames;
    private javax.swing.JLabel patientId;
    private javax.swing.JLabel patientName;
    private javax.swing.JPanel pnlDicomPatientData;
    private javax.swing.JLabel report;
    private javax.swing.JLabel sex;
    private javax.swing.JTabbedPane tbpCase;
    private javax.swing.JTextField txtComments;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtIssuerOfPatientId;
    private javax.swing.JTextField txtMothersBirthName;
    private javax.swing.JTextField txtOtherPatientId;
    private javax.swing.JTextField txtOtherPatientNames;
    private javax.swing.JTextField txtPatientId;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextArea txtReport;
    private javax.swing.JTextField txtSex;
    private javax.swing.JTextField txtTypeOfPatientId;
    private javax.swing.JLabel typeOfPatientId;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
