/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DataProcLogListView.java
 *
 * Created on 2011.03.28., 10:20:44
 */

package casemodule.view;

import casemodule.iview.IDataProcLogListView;
import casemodule.viewmodel.DataProcLogListViewModel;
import commonmodule.view.TDSColor;
import converter.DateTimeConverter;

/**
 *
 * @author vincze.attila
 */
public class DataProcLogListView extends javax.swing.JInternalFrame implements IDataProcLogListView {

    private DataProcLogListViewModel viewModel;
    /** Creates new form DataProcLogListView */
    public DataProcLogListView() {
        viewModel = new DataProcLogListViewModel(this);
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
        thpSearch.getBtnHide().addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpnSearch.setCollapsed(!cpnSearch.isCollapsed());
            }
        });
        thpDetail.getBtnHide().addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tspHospital.setDividerLocation(thpDetail.isUp() ? tspHospital.getHeight() - 270 : tspHospital.getHeight() - 32);
            }
        });
        cpnSearch.getContentPane().setBackground(TDSColor.color3);
        thpDetail.setUp(false);
    }

    public DataProcLogListViewModel getViewModel() {
        return viewModel;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        thpSearch = new commonmodule.view.TDSHeaderPanel();
        jPanel6 = new javax.swing.JPanel();
        cpnSearch = new org.jdesktop.swingx.JXCollapsiblePane();
        btnAll = new javax.swing.JButton();
        btnSearch = new commonmodule.view.TDSSearchButton();
        tDSTextField1 = new commonmodule.view.TDSTextField();
        lblSearchName = new javax.swing.JLabel();
        tspHospital = new commonmodule.view.TDSSplitPane();
        jPanel30 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEntities = new commonmodule.view.TDSTable();
        jPanel32 = new javax.swing.JPanel();
        thpDetail = new commonmodule.view.TDSHeaderPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        lblEntryGeneration = new commonmodule.view.TDSLabel();
        tDSTextField2 = new commonmodule.view.TDSTextField();
        lblEntryType = new commonmodule.view.TDSLabel();
        tDSTextField3 = new commonmodule.view.TDSTextField();
        lblEntry = new commonmodule.view.TDSLabel();
        tDSTextField4 = new commonmodule.view.TDSTextField();
        lblSender = new commonmodule.view.TDSLabel();
        tDSTextField5 = new commonmodule.view.TDSTextField();
        lblNote = new commonmodule.view.TDSLabel();
        tDSTextField6 = new commonmodule.view.TDSTextField();
        lblRecordUid = new commonmodule.view.TDSLabel();
        tDSTextField7 = new commonmodule.view.TDSTextField();
        lblDisplayedByUser = new commonmodule.view.TDSLabel();
        tDSTextField8 = new commonmodule.view.TDSTextField();
        lblDisplayedByClient = new commonmodule.view.TDSLabel();
        tDSTextField9 = new commonmodule.view.TDSTextField();
        lblTableName = new commonmodule.view.TDSLabel();
        tDSTextField10 = new commonmodule.view.TDSTextField();
        lblColumnName = new commonmodule.view.TDSLabel();
        tDSTextField11 = new commonmodule.view.TDSTextField();
        lblFromValue = new commonmodule.view.TDSLabel();
        tDSTextField12 = new commonmodule.view.TDSTextField();
        lblToValue = new commonmodule.view.TDSLabel();
        tDSTextField13 = new commonmodule.view.TDSTextField();
        jPanel5 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(238, 243, 250));
        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(20, 20, 20, 20, new java.awt.Color(207, 224, 242)), javax.swing.BorderFactory.createLineBorder(java.awt.Color.gray)));

        jPanel1.setBackground(new java.awt.Color(238, 243, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(25, 30, 30, 30, new java.awt.Color(238, 243, 250)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.info}"), thpSearch, org.jdesktop.beansbinding.BeanProperty.create("info"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.searchCriteria}"), thpSearch, org.jdesktop.beansbinding.BeanProperty.create("searchCriteria"));
        bindingGroup.addBinding(binding);

        jPanel1.add(thpSearch, java.awt.BorderLayout.PAGE_START);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout());

        cpnSearch.setAnimated(false);
        cpnSearch.setBackground(new java.awt.Color(245, 249, 254));
        cpnSearch.setPreferredSize(new java.awt.Dimension(562, 50));
        cpnSearch.getContentPane().setLayout(new java.awt.GridBagLayout());

        btnAll.setAction(viewModel.getFindAllAction());
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("casemodule/bundle/DataProcLogListBundle"); // NOI18N
        btnAll.setText(bundle.getString("DataProcLogListView.btnAll.text")); // NOI18N
        btnAll.setPreferredSize(new java.awt.Dimension(90, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 35);
        cpnSearch.getContentPane().add(btnAll, gridBagConstraints);

        btnSearch.setAction(viewModel.getFindAction());
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casemodule/image/search.png"))); // NOI18N
        btnSearch.setText(bundle.getString("DataProcLogListView.btnSearch.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        cpnSearch.getContentPane().add(btnSearch, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        cpnSearch.getContentPane().add(tDSTextField1, gridBagConstraints);

        lblSearchName.setText(bundle.getString("DataProcLogListView.lblSearchName.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        cpnSearch.getContentPane().add(lblSearchName, gridBagConstraints);

        jPanel6.add(cpnSearch, java.awt.BorderLayout.PAGE_START);

        tspHospital.setDividerLocation(250);

        jPanel30.setOpaque(false);
        jPanel30.setPreferredSize(new java.awt.Dimension(190, 200));
        jPanel30.setLayout(new java.awt.GridBagLayout());

        tblEntities.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.entityList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tblEntities);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${dataProcLog.caseItBelongsTo.tdsCaseUniqueId}"));
        columnBinding.setColumnName("Data Proc Log.case It Belongs To.tds Case Unique Id");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entryGeneration}"));
        columnBinding.setColumnName("Entry Generation");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${recordUid}"));
        columnBinding.setColumnName("Record Uid");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${displayedByClient}"));
        columnBinding.setColumnName("Displayed By Client");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${displayedByUser}"));
        columnBinding.setColumnName("Displayed By User");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entry}"));
        columnBinding.setColumnName("Entry");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${entryType}"));
        columnBinding.setColumnName("Entry Type");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${note}"));
        columnBinding.setColumnName("Note");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sender}"));
        columnBinding.setColumnName("Sender");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tableName}"));
        columnBinding.setColumnName("Table Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${columnName}"));
        columnBinding.setColumnName("Column Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fromValue}"));
        columnBinding.setColumnName("From Value");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${toValue}"));
        columnBinding.setColumnName("To Value");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.selectedEntity}"), tblEntities, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.selectedIndex}"), tblEntities, org.jdesktop.beansbinding.BeanProperty.create("selectedIndex"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(tblEntities);
        tblEntities.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title0")); // NOI18N
        tblEntities.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title1")); // NOI18N
        tblEntities.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title2_1")); // NOI18N
        tblEntities.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title3_1")); // NOI18N
        tblEntities.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title4")); // NOI18N
        tblEntities.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title5")); // NOI18N
        tblEntities.getColumnModel().getColumn(6).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title6")); // NOI18N
        tblEntities.getColumnModel().getColumn(7).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title7")); // NOI18N
        tblEntities.getColumnModel().getColumn(8).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title8")); // NOI18N
        tblEntities.getColumnModel().getColumn(9).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title9")); // NOI18N
        tblEntities.getColumnModel().getColumn(10).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title10")); // NOI18N
        tblEntities.getColumnModel().getColumn(11).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title11")); // NOI18N
        tblEntities.getColumnModel().getColumn(12).setHeaderValue(bundle.getString("DataProcLogListView.tblEntities.columnModel.title12")); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        jPanel30.add(jScrollPane2, gridBagConstraints);

        tspHospital.setLeftComponent(jPanel30);

        jPanel32.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 0, 0, 0, new java.awt.Color(238, 243, 250)));
        jPanel32.setOpaque(false);
        jPanel32.setMinimumSize(new java.awt.Dimension(333, 25));
        jPanel32.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel32.setLayout(new java.awt.BorderLayout());

        thpDetail.setInfo(bundle.getString("DataProcLogListView.thpDetail.info")); // NOI18N
        thpDetail.setSearchCriteria(bundle.getString("DataProcLogListView.thpDetail.searchCriteria")); // NOI18N
        thpDetail.setUp(false);
        jPanel32.add(thpDetail, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBorder(null);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1000, 150));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1000, 150));

        jPanel33.setOpaque(false);
        jPanel33.setMinimumSize(new java.awt.Dimension(900, 200));
        jPanel33.setPreferredSize(new java.awt.Dimension(900, 150));
        jPanel33.setLayout(new java.awt.BorderLayout());

        jPanel34.setBackground(new java.awt.Color(245, 249, 254));
        jPanel34.setPreferredSize(new java.awt.Dimension(690, 60));
        jPanel34.setLayout(new java.awt.GridBagLayout());

        lblEntryGeneration.setText(bundle.getString("DataProcLogListView.lblEntryGeneration.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        jPanel34.add(lblEntryGeneration, gridBagConstraints);

        tDSTextField2.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.entryGeneration}"), tDSTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        binding.setConverter(new DateTimeConverter());
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        jPanel34.add(tDSTextField2, gridBagConstraints);

        lblEntryType.setText(bundle.getString("DataProcLogListView.lblEntryType.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 30, 0, 0);
        jPanel34.add(lblEntryType, gridBagConstraints);

        tDSTextField3.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.entryType}"), tDSTextField3, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 0, 0);
        jPanel34.add(tDSTextField3, gridBagConstraints);

        lblEntry.setText(bundle.getString("DataProcLogListView.lblEntry.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(lblEntry, gridBagConstraints);

        tDSTextField4.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.entry}"), tDSTextField4, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField4, gridBagConstraints);

        lblSender.setText(bundle.getString("DataProcLogListView.lblSender.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 0);
        jPanel34.add(lblSender, gridBagConstraints);

        tDSTextField5.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.sender}"), tDSTextField5, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField5, gridBagConstraints);

        lblNote.setText(bundle.getString("DataProcLogListView.lblNote.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(lblNote, gridBagConstraints);

        tDSTextField6.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.note}"), tDSTextField6, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField6, gridBagConstraints);

        lblRecordUid.setText(bundle.getString("DataProcLogListView.lblRecordUid.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 0);
        jPanel34.add(lblRecordUid, gridBagConstraints);

        tDSTextField7.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.recordUid}"), tDSTextField7, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField7, gridBagConstraints);

        lblDisplayedByUser.setText(bundle.getString("DataProcLogListView.lblDisplayedByUser.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(lblDisplayedByUser, gridBagConstraints);

        tDSTextField8.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.displayedByUser}"), tDSTextField8, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField8, gridBagConstraints);

        lblDisplayedByClient.setText(bundle.getString("DataProcLogListView.lblDisplayedByClient.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 0);
        jPanel34.add(lblDisplayedByClient, gridBagConstraints);

        tDSTextField9.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.displayedByClient}"), tDSTextField9, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField9, gridBagConstraints);

        lblTableName.setText(bundle.getString("DataProcLogListView.lblTableName.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(lblTableName, gridBagConstraints);

        tDSTextField10.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.tableName}"), tDSTextField10, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField10, gridBagConstraints);

        lblColumnName.setText(bundle.getString("DataProcLogListView.lblColumnName.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 0);
        jPanel34.add(lblColumnName, gridBagConstraints);

        tDSTextField11.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.columnName}"), tDSTextField11, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField11, gridBagConstraints);

        lblFromValue.setText(bundle.getString("DataProcLogListView.lblFromValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(lblFromValue, gridBagConstraints);

        tDSTextField12.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.fromValue}"), tDSTextField12, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField12, gridBagConstraints);

        lblToValue.setText(bundle.getString("DataProcLogListView.lblToValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 30, 0, 0);
        jPanel34.add(lblToValue, gridBagConstraints);

        tDSTextField13.setEditable(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.detailedEntity.toValue}"), tDSTextField13, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 0, 0);
        jPanel34.add(tDSTextField13, gridBagConstraints);

        jPanel33.add(jPanel34, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(245, 249, 254));
        jPanel5.setMinimumSize(new java.awt.Dimension(120, 50));
        jPanel5.setPreferredSize(new java.awt.Dimension(160, 50));
        jPanel5.setLayout(new java.awt.GridBagLayout());
        jPanel33.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setViewportView(jPanel33);

        jPanel32.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tspHospital.setRightComponent(jPanel32);

        jPanel6.add(tspHospital, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAll;
    private commonmodule.view.TDSSearchButton btnSearch;
    private org.jdesktop.swingx.JXCollapsiblePane cpnSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private commonmodule.view.TDSLabel lblColumnName;
    private commonmodule.view.TDSLabel lblDisplayedByClient;
    private commonmodule.view.TDSLabel lblDisplayedByUser;
    private commonmodule.view.TDSLabel lblEntry;
    private commonmodule.view.TDSLabel lblEntryGeneration;
    private commonmodule.view.TDSLabel lblEntryType;
    private commonmodule.view.TDSLabel lblFromValue;
    private commonmodule.view.TDSLabel lblNote;
    private commonmodule.view.TDSLabel lblRecordUid;
    private javax.swing.JLabel lblSearchName;
    private commonmodule.view.TDSLabel lblSender;
    private commonmodule.view.TDSLabel lblTableName;
    private commonmodule.view.TDSLabel lblToValue;
    private commonmodule.view.TDSTextField tDSTextField1;
    private commonmodule.view.TDSTextField tDSTextField10;
    private commonmodule.view.TDSTextField tDSTextField11;
    private commonmodule.view.TDSTextField tDSTextField12;
    private commonmodule.view.TDSTextField tDSTextField13;
    private commonmodule.view.TDSTextField tDSTextField2;
    private commonmodule.view.TDSTextField tDSTextField3;
    private commonmodule.view.TDSTextField tDSTextField4;
    private commonmodule.view.TDSTextField tDSTextField5;
    private commonmodule.view.TDSTextField tDSTextField6;
    private commonmodule.view.TDSTextField tDSTextField7;
    private commonmodule.view.TDSTextField tDSTextField8;
    private commonmodule.view.TDSTextField tDSTextField9;
    private commonmodule.view.TDSTable tblEntities;
    private commonmodule.view.TDSHeaderPanel thpDetail;
    private commonmodule.view.TDSHeaderPanel thpSearch;
    private commonmodule.view.TDSSplitPane tspHospital;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
