/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SystemMessageListView.java
 *
 * Created on 2010.12.12., 23:16:04
 */
package casemodule.view;

import casemodule.iview.ISystemMessageListView;
import casemodule.viewmodel.SystemMessageListViewModel;
import converter.DateTimeTableCellRenderer;
import converter.TDSListCellRenderer;

/**
 *
 * @author vincze.attila
 */
public class SystemMessageListView extends javax.swing.JInternalFrame
        implements ISystemMessageListView {

    private SystemMessageListViewModel viewModel;
    /** Creates new form SystemMessageListView */
    public SystemMessageListView() {
        viewModel = new SystemMessageListViewModel(this);
        initComponents();
    }

    public SystemMessageListViewModel getViewModel() {
        return viewModel;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnlSearch = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        cmbUser = new javax.swing.JComboBox();
        systemMessageType = new javax.swing.JLabel();
        cmbSystemMessageType = new javax.swing.JComboBox();
        pnlMessage = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        pnlList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntities = new javax.swing.JTable();

        setBackground(new java.awt.Color(227, 239, 251));
        setBorder(null);
        setClosable(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("casemodule/bundle/CaseModuleBundle"); // NOI18N
        pnlSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CaseListView.pnlSearch.border.title"))); // NOI18N
        pnlSearch.setOpaque(false);
        pnlSearch.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        user.setText(bundle.getString("CaseListView.caseStatus.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(user, gridBagConstraints);

        btnSearch.setAction(viewModel.getFindAction());
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casemodule/image/search.png"))); // NOI18N
        btnSearch.setText(bundle.getString("CaseListView.btnSearch.text")); // NOI18N
        btnSearch.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(btnSearch, gridBagConstraints);

        cmbUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbUser.setPreferredSize(new java.awt.Dimension(150, 20));
        cmbUser.setRenderer(new TDSListCellRenderer());

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.userList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cmbUser);
        bindingGroup.addBinding(jComboBoxBinding);
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.selectedUser}"), cmbUser, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(cmbUser, gridBagConstraints);

        systemMessageType.setText(bundle.getString("SystemMessageListView.systemMessageType.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(systemMessageType, gridBagConstraints);

        cmbSystemMessageType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbSystemMessageType.setPreferredSize(new java.awt.Dimension(150, 20));
        cmbSystemMessageType.setRenderer(new TDSListCellRenderer());

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.systemMessageTypeList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, cmbSystemMessageType);
        bindingGroup.addBinding(jComboBoxBinding);
        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.selectedSystemMessageType}"), cmbSystemMessageType, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(cmbSystemMessageType, gridBagConstraints);

        pnlSearch.add(jPanel1, java.awt.BorderLayout.WEST);

        pnlMessage.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CaseListView.pnlMessage.border.title"))); // NOI18N
        pnlMessage.setOpaque(false);
        pnlMessage.setPreferredSize(new java.awt.Dimension(17, 50));
        pnlMessage.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridBagLayout());

        lblMessage.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMessage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.message}"), lblMessage, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel2.add(lblMessage, gridBagConstraints);

        pnlMessage.add(jPanel2, java.awt.BorderLayout.WEST);

        pnlList.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CaseListView.pnlList.border.title"))); // NOI18N
        pnlList.setOpaque(false);

        tblEntities.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.systemMessageList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tblEntities);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emailAddress}"));
        columnBinding.setColumnName("Email Address");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${emailWasSent}"));
        columnBinding.setColumnName("Email Was Sent");
        columnBinding.setColumnClass(Boolean.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${messageText}"));
        columnBinding.setColumnName("Message Text");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${sent}"));
        columnBinding.setColumnName("Sent");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${recipient.name}"));
        columnBinding.setColumnName("Recipient.name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        jTableBinding.setSourceUnreadableValue(java.util.Collections.emptyList());
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblEntities);
        tblEntities.getColumnModel().getColumn(0).setMinWidth(20);
        tblEntities.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblEntities.getColumnModel().getColumn(0).setMaxWidth(40);
        tblEntities.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("SystemMessageListView.tblEntities.columnModel.title0")); // NOI18N
        tblEntities.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("SystemMessageListView.tblEntities.columnModel.title1")); // NOI18N
        tblEntities.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("SystemMessageListView.tblEntities.columnModel.title2")); // NOI18N
        tblEntities.getColumnModel().getColumn(3).setHeaderValue(bundle.getString("SystemMessageListView.tblEntities.columnModel.title3")); // NOI18N
        tblEntities.getColumnModel().getColumn(4).setHeaderValue(bundle.getString("SystemMessageListView.tblEntities.columnModel.title4")); // NOI18N
        tblEntities.getColumnModel().getColumn(4).setCellRenderer(new DateTimeTableCellRenderer());
        tblEntities.getColumnModel().getColumn(5).setHeaderValue(bundle.getString("SystemMessageListView.tblEntities.columnModel.title5")); // NOI18N
        tblEntities.getColumnModel().getColumn(5).setCellRenderer(null);

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
            .addComponent(pnlMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 799, Short.MAX_VALUE)
            .addComponent(pnlList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox cmbSystemMessageType;
    private javax.swing.JComboBox cmbUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPanel pnlList;
    private javax.swing.JPanel pnlMessage;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JLabel systemMessageType;
    private javax.swing.JTable tblEntities;
    private javax.swing.JLabel user;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
