/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * WaitingCaseListView.java
 *
 * Created on 2010.12.13., 8:46:07
 */
package casemodule.view;

import casemodule.iview.IWaitingCaseListView;
import casemodule.viewmodel.WaitingCaseListViewModel;

/**
 *
 * @author vincze.attila
 */
public class WaitingCaseListView extends javax.swing.JInternalFrame implements IWaitingCaseListView {

    private WaitingCaseListViewModel viewModel;

    /** Creates new form WaitingCaseListView */
    public WaitingCaseListView() {
        viewModel = new WaitingCaseListViewModel(this);
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).setNorthPane(null);
        caseStatus.setVisible(false);
        cmbCaseStatus.setVisible(false);
    }

    public WaitingCaseListViewModel getViewModel() {
        return viewModel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        pnlSearch = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        caseStatus = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        cmbCaseStatus = new javax.swing.JComboBox();
        pnlMessage = new javax.swing.JPanel();
        lblMessage = new javax.swing.JLabel();
        pnlList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEntities = new javax.swing.JTable();

        setBackground(new java.awt.Color(227, 239, 251));
        setBorder(null);
        setClosable(true);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("casemodule/bundle/CaseModuleBundle"); // NOI18N
        pnlSearch.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CaseListView.pnlSearch.border.title"))); // NOI18N
        pnlSearch.setOpaque(false);
        pnlSearch.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        caseStatus.setText(bundle.getString("CaseListView.caseStatus.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(caseStatus, gridBagConstraints);

        btnSearch.setAction(viewModel.getFindAction());
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/casemodule/image/search.png"))); // NOI18N
        btnSearch.setText(bundle.getString("CaseListView.btnSearch.text")); // NOI18N
        btnSearch.setPreferredSize(new java.awt.Dimension(120, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(btnSearch, gridBagConstraints);

        cmbCaseStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCaseStatus.setPreferredSize(new java.awt.Dimension(150, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(cmbCaseStatus, gridBagConstraints);

        pnlSearch.add(jPanel1, java.awt.BorderLayout.WEST);

        pnlMessage.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CaseListView.pnlMessage.border.title"))); // NOI18N
        pnlMessage.setOpaque(false);

        lblMessage.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblMessage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${viewModel.message}"), lblMessage, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout pnlMessageLayout = new javax.swing.GroupLayout(pnlMessage);
        pnlMessage.setLayout(pnlMessageLayout);
        pnlMessageLayout.setHorizontalGroup(
            pnlMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage)
                .addContainerGap(825, Short.MAX_VALUE))
        );
        pnlMessageLayout.setVerticalGroup(
            pnlMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlList.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("CaseListView.pnlList.border.title"))); // NOI18N
        pnlList.setOpaque(false);

        tblEntities.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${viewModel.caseList}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tblEntities);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tdsCaseUniqueId}"));
        columnBinding.setColumnName("Tds Case Unique Id");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${transferredToServer}"));
        columnBinding.setColumnName("Transferred To Server");
        columnBinding.setColumnClass(java.util.Date.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(tblEntities);
        tblEntities.getColumnModel().getColumn(0).setMinWidth(20);
        tblEntities.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblEntities.getColumnModel().getColumn(0).setMaxWidth(40);
        tblEntities.getColumnModel().getColumn(0).setHeaderValue(bundle.getString("WaitingCaseListView.tblEntities.columnModel.title0")); // NOI18N
        tblEntities.getColumnModel().getColumn(1).setHeaderValue(bundle.getString("WaitingCaseListView.tblEntities.columnModel.title1")); // NOI18N
        tblEntities.getColumnModel().getColumn(2).setHeaderValue(bundle.getString("WaitingCaseListView.tblEntities.columnModel.title2")); // NOI18N

        javax.swing.GroupLayout pnlListLayout = new javax.swing.GroupLayout(pnlList);
        pnlList.setLayout(pnlListLayout);
        pnlListLayout.setHorizontalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
        );
        pnlListLayout.setVerticalGroup(
            pnlListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
            .addComponent(pnlMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel caseStatus;
    private javax.swing.JComboBox cmbCaseStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JPanel pnlList;
    private javax.swing.JPanel pnlMessage;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JTable tblEntities;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
