/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HospitalHistoryCasePanel.java
 *
 * Created on 2011.05.06., 11:50:06
 */
package commonmodule.view;

import javax.swing.JLabel;
import javax.swing.JTextArea;

/**
 *
 * @author vincze.attila
 */
public class HospitalHistoryCasePanel extends javax.swing.JPanel {

    /** Creates new form HospitalHistoryCasePanel */
    public HospitalHistoryCasePanel() {
        initComponents();
    }

    public JLabel getLblHistoryNumber() {
        return lblHistoryNumber;
    }

    public JTextArea getTaStudyStructure() {
        return taStudyStructure;
    }

    public ITSButton getBtnReferral() {
        return btnReferral;
    }

    public ITSButton getBtnReport() {
        return btnReport;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPasswordField1 = new javax.swing.JPasswordField();
        tDSCheckBox1 = new commonmodule.view.ITSCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblHistoryNumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnReferral = new commonmodule.view.ITSButton();
        btnReport = new commonmodule.view.ITSButton();
        taStudyStructure = new javax.swing.JTextArea();

        jPasswordField1.setText("jPasswordField1");

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        tDSCheckBox1.setText("View images");
        tDSCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        add(tDSCheckBox1, gridBagConstraints);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("(individual past study from hospital)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        lblHistoryNumber.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblHistoryNumber.setText("1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        jPanel1.add(lblHistoryNumber, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("History");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel1.add(jLabel3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(jPanel1, gridBagConstraints);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 23));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnReferral.setText("View referral");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jPanel2.add(btnReferral, gridBagConstraints);

        btnReport.setText("View report");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
        jPanel2.add(btnReport, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        add(jPanel2, gridBagConstraints);

        taStudyStructure.setBackground(new java.awt.Color(232, 238, 247));
        taStudyStructure.setColumns(20);
        taStudyStructure.setEditable(false);
        taStudyStructure.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        taStudyStructure.setRows(5);
        taStudyStructure.setTabSize(3);
        taStudyStructure.setBorder(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 0);
        add(taStudyStructure, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private commonmodule.view.ITSButton btnReferral;
    private commonmodule.view.ITSButton btnReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblHistoryNumber;
    private commonmodule.view.ITSCheckBox tDSCheckBox1;
    private javax.swing.JTextArea taStudyStructure;
    // End of variables declaration//GEN-END:variables
}
