/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TDSSearchPanel.java
 *
 * Created on 2011.02.10., 20:08:10
 */

package commonmodule.view;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import javax.swing.Action;
import javax.swing.Icon;
import javax.swing.JButton;

/**
 *
 * @author vincze.attila
 */
public class ITSHeaderPanel extends javax.swing.JPanel {

    private Icon upIcon;
    private Icon downIcon;
    private boolean up;
    private Action iconAction;
    /** Creates new form TDSSearchPanel */
    public ITSHeaderPanel() {
        initComponents();
        upIcon = new javax.swing.ImageIcon(getClass().getResource("/commonmodule/image/felnyil.png"));
        downIcon = new javax.swing.ImageIcon(getClass().getResource("/commonmodule/image/lenyil.png"));
        up = true;
    }

    @Override
    protected void paintComponent(Graphics g) {
        if (!isOpaque()) {
            super.paintComponent(g);
            return;
        }

        Graphics2D g2d = (Graphics2D) g;
        int w = getWidth();
        int h = getHeight();

        Color color1 = new Color(199,223,249);
        Color color2 = new Color(227,239,251);// color1.brighter();
        GradientPaint gp = new GradientPaint(
                w, 0, color2,
                0, 0, color1);

        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);

        setOpaque(false);
        super.paintComponent(g);
        setOpaque(true);

    }

    public JButton getBtnHide() {
        return btnHide;
    }

    public boolean isUp() {
        return up;
    }

    public void setUp(boolean up) {
        this.up = up;
        btnHide.setIcon(up ? upIcon : downIcon);
    }

    public Action getIconAction() {
        return iconAction;
    }

    public void setIconAction(Action iconAction) {
        this.iconAction = iconAction;
    }

    public String getInfo() {
        return lblInfo.getText();
    }

    public void setInfo(String info) {
        lblInfo.setText(info);
    }

    public String getSearchCriteria() {
        return lblSearchCriteria.getText();
    }

    public void setSearchCriteria(String searchCriteria) {
        lblSearchCriteria.setText(searchCriteria);
    }

    public boolean isBtnHideVisible(){
        return btnHide.isVisible();
    }

    public void setBtnHideVisible(boolean visible){
        btnHide.setVisible(visible);
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblInfo = new javax.swing.JLabel();
        lblSearchCriteria = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnHide = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(56, 25));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(34, 22));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblInfo.setForeground(new java.awt.Color(0, 0, 128));
        lblInfo.setText("Keresés");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(lblInfo, gridBagConstraints);

        lblSearchCriteria.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblSearchCriteria.setForeground(new java.awt.Color(0, 0, 128));
        lblSearchCriteria.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 0);
        jPanel1.add(lblSearchCriteria, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setOpaque(false);

        btnHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commonmodule/image/felnyil.png"))); // NOI18N
        btnHide.setFocusable(false);
        btnHide.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHide.setPreferredSize(new java.awt.Dimension(20, 20));
        btnHide.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideActionPerformed(evt);
            }
        });
        jToolBar1.add(btnHide);

        add(jToolBar1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideActionPerformed
        // TODO add your handling code here:
        btnHide.setIcon(btnHide.getIcon().equals(downIcon) ? upIcon : downIcon);
        setUp(!up);
    }//GEN-LAST:event_btnHideActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHide;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblSearchCriteria;
    // End of variables declaration//GEN-END:variables

}
