/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TDSPanel.java
 *
 * Created on 2011.03.15., 10:21:58
 */
package commonmodule.view;

/**
 *
 * @author vincze.attila
 */
public class ITSPanel extends javax.swing.JPanel {

    private String series;
    /** Creates new form TDSPanel */
    public ITSPanel() {

        //initComponents();
        setOpaque(false);

    }

    public boolean isComponentVisible() {
        return isVisible();
    }

    public void setComponentVisible(boolean componentVisible) {
        setVisible(componentVisible);
    }

    public String getSeries() {
        return series;
    }

    public void setSeries(String series) {
        this.series = series;
        System.out.println(series);
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
