/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TDSVSeparatorPanel.java
 *
 * Created on 2011.02.17., 10:18:10
 */

package commonmodule.view;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author vincze.attila
 */
public class TDSVSeparatorPanel extends javax.swing.JPanel {

    /** Creates new form TDSVSeparatorPanel */
    public TDSVSeparatorPanel() {
        initComponents();
    }


    @Override
    protected void paintComponent(Graphics g) {
        if (!isOpaque()) {
            super.paintComponent(g);
            return;
        }

        Graphics2D g2d = (Graphics2D) g;
        int w = getWidth();
        int h = getHeight();

        //Color color1 = getBackground();
        //Color color2 = color1.darker();
        Color color1 = new Color(32,74,135);
        Color color2 = new Color(243,248,254);// color1.brighter();
        GradientPaint gp = new GradientPaint(
                0, 0, color2,
                0, h, color1);

        GradientPaint gp2 = new GradientPaint(
                0, 0, color1,
                0, h, color2);


        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h/2);
        g2d.setPaint(gp2);
        g2d.fillRect(0, h/2, w, h);

        setOpaque(false);
        super.paintComponent(g);
        setOpaque(true);

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
