/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 2011.04.12., 12:16:05
 */

package test;

/**
 *
 * @author vincze.attila
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tDSEditorPane1 = new commonmodule.view.ITSEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tDSEditorPane1.setContentType("text/html");
        tDSEditorPane1.setText("<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n    <title></title>\n</head>\n<body>\n    <table style=\"width: 100%;\">\n        <tr>\n            <td>\n                Study 1\n            </td>\n            <td colspan=\"5\">\n                (Accession number - 1234654789, Study date and time - 21101,1212,,12)\n            </td>\n        </tr>\n        <tr>\n            <td>\n               \n            </td>\n            <td>\n                Series 1\n            </td>\n            <td>\n                MR\n            </td>\n            <td>\n                Neck\n            </td>\n            <td>\n                Correnction: \n            </td>\n            <td>\n                <select id=\"Select1\">\n                    <option>aa</option>\n                    <option>bb</option>\n                </select>\n            </td>\n        </tr>\n    </table>\n</body>\n</html>\n");
        jScrollPane1.setViewportView(tDSEditorPane1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private commonmodule.view.ITSEditorPane tDSEditorPane1;
    // End of variables declaration//GEN-END:variables

}
