/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 2010.11.22., 11:21:48
 */
package casemodule.downloading;

import casemodule.dto.DicomImageDTO;
import event.DicomDataSetDownloadedEvent;
import event.DicomDataSetDownloadedEventListener;
import event.ITSEventManager;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author vincze.attila
 */
public class LocalCaseDownloaderFrame extends javax.swing.JFrame implements DicomDataSetDownloadedEventListener {

    /** Creates new form NewJFrame */
    public LocalCaseDownloaderFrame() {
        initComponents();
        ITSEventManager.getEventListenerList().add(DicomDataSetDownloadedEventListener.class, this);
        LocalCaseDownloader.getInstance();
//        Format formatter = new SimpleDateFormat("yyyyMMddhhmmssSSS");
//
//        Calendar c1 = Calendar.getInstance();
//        c1.setTime(new Date());
//        c1.add(Calendar.DATE, 1);
//        System.out.println(formatter.format(c1.getTime()));

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LocalCaseDownloaderFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void eventOccured(DicomDataSetDownloadedEvent event) {

        if (event.getSource() instanceof String) {
            jTextField1.setText(event.getSource().toString());
        } else {
            jTextField1.setText(((DicomImageDTO) event.getSource()).getInstanceUid());
        }
    }
}
