/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TDSTreeImage.java
 *
 * Created on 2011.04.29., 15:08:45
 */
package viewernavigator.view;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;

/**
 *
 * @author vincze.attila
 */
public class TDSTreeImage extends javax.swing.JPanel {

    private BufferedImage image;
    private Color infoColor;
    private Color iconBorderColor;

    /** Creates new form TDSTreeImage */
    public TDSTreeImage() {
        this(null, null, null, null, Color.CYAN, Color.BLACK);

    }

    public TDSTreeImage(BufferedImage image, String modality, String bodyRegion, Integer seriesImageNumber, Color infoColor, Color iconBorderColor) {
        this.image = image;
        this.infoColor = infoColor;
        this.iconBorderColor = iconBorderColor;
        int w = image.getWidth() + 2;
        int h = image.getHeight() + 10;
        setPreferredSize(new Dimension(w, h));
        initComponents();
        setPreferredSize(new Dimension(w, h));
        lblModality.setText(modality);
        lblBodyRegion.setText(bodyRegion);
        lblSeriesImageNumber.setText(seriesImageNumber.toString());

    }

    public TDSTreeImage(BufferedImage image) {
        this(image, null, null, null, Color.CYAN, Color.BLACK);
    }

    @Override
    protected void paintComponent(Graphics g) {
//        if (!isOpaque()) {
//            super.paintComponent(g);
//            return;
//        }

        Graphics2D g2d = (Graphics2D) g;
        int w = image.getWidth();
        int h = image.getHeight();

        //BufferedImage bi = ImageIO.read(getClass().getResourceAsStream("/image/eszkoztarhatter1.png"));
        g2d.drawImage(image, 1, 5, w, h, null);
        g2d.setColor(iconBorderColor);
        //g2d.setPaint(new pa)
        //g2d.setStroke(new BasicStroke(1));
        //g2d.drawRect(1, 5, w, h);
        setOpaque(false);
        super.paintComponent(g);
        setOpaque(true);


    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblModality = new javax.swing.JLabel();
        lblSeriesImageNumber = new javax.swing.JLabel();
        lblBodyRegion = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createLineBorder(iconBorderColor)));
        setMaximumSize(new java.awt.Dimension(130, 130));
        setMinimumSize(new java.awt.Dimension(130, 130));
        setPreferredSize(new java.awt.Dimension(130, 130));
        setLayout(new java.awt.GridBagLayout());

        lblModality.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblModality.setForeground(infoColor);
        lblModality.setText("MR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lblModality, gridBagConstraints);

        lblSeriesImageNumber.setFont(new java.awt.Font("Arial", 0, 12));
        lblSeriesImageNumber.setForeground(infoColor);
        lblSeriesImageNumber.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        add(lblSeriesImageNumber, gridBagConstraints);

        lblBodyRegion.setFont(new java.awt.Font("Arial", 0, 10));
        lblBodyRegion.setForeground(infoColor);
        lblBodyRegion.setText("Head");
        lblBodyRegion.setMaximumSize(new java.awt.Dimension(100, 15));
        lblBodyRegion.setPreferredSize(new java.awt.Dimension(100, 15));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        add(lblBodyRegion, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBodyRegion;
    private javax.swing.JLabel lblModality;
    private javax.swing.JLabel lblSeriesImageNumber;
    // End of variables declaration//GEN-END:variables
}
